config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  resources :pages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.all
  end

  def new
    @page = Page.new
  end

  def create
    Page.create(page_params)
    redirect_to root_path
  end

  private

  def page_params
    params.require(:page).permit(:name, :description)
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnimalBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <%= link_to 'Animal Blog', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item">
            <%= link_to 'New Animal', new_page_path, class: 'nav-link' %>
          </li>
        </ul>  
      </div>
    </nav>   

    <%= yield %>
  </body>
</html>

app/views/pages/index.html.erb
<h2>Welcome to my blog</h2>
  <p>This blog will be about my love for animals and show links to information about fostering. I'll have pictures of the previous foster animals that I had in my care and the duration of the time they were with me. There will be links to articles about the changing laws in regards to fostering pets. </p>

<% @pages.each do |page| %>
  <div class="booyah-box col-10 offset-1">
    <h1><%= page.name %></h1>
    
    <p><%= page.description %></p><br />
  </div>
<% end %>

app/views/pages/new.html.erb
<div class="booyah-box col-10 offset-1">  
  <h1>Enter your animal here</h1>
  <%= simple_form_for @page do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <br />
    <%= f.submit 'Add me', class: 'btn btn-primary' %>
  <% end %>
</div>